Vagrant.configure("2") do |config|
  # AlmaLinux VM 2
  config.vm.define "alma-worker" do |node|
    node.vm.box = "bento/almalinux-9"
    node.vm.hostname = "alma-worker"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "alma-worker"
      vb.memory = "4096"
      vb.cpus = 2
    end

    node.vm.network "private_network", ip: "192.168.56.30"
    
    # File syncing and provisioning
    node.vm.synced_folder "~/Projects/project-IaC/alma-worker/files", "/vagrant_data", type: "rsync"
    
    # Provisioning with shell script
    node.vm.provision "shell", path: "provision/alma_worker_conf.sh"
  end
end
