apiVersion: v1
kind: Service
metadata:
  name: post-app-service
spec:
  selector:
    app: post-app
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30700
  type: NodePort
