apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30100
  type: NodePort
[root@alma-cluster vagrant_data]# cat app1-deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
        - name: post-app
          image: nahiyan83bjit/collections:post_app
          ports:
            - containerPort: 7000
