apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          hostPath:
            path: /vagrant_data/dump.sql
