Vagrant.configure("2") do |config|
  # AlmaLinux VM 1
  config.vm.define "alma-cluster" do |node|
    node.vm.box = "bento/almalinux-9"
    node.vm.hostname = "alma-cluster"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "alma-cluster"
      vb.memory = "4096"
      vb.cpus = 2
    end

    node.vm.network "private_network", ip: "192.168.56.20"
    
    # File syncing and provisioning
    node.vm.synced_folder "~/Projects/project-IaC/alma-cluster/files", "/vagrant_data", type: "rsync"
        
    # Provisioning with shell script
    node.vm.provision "shell", path: "provision/alma_common_conf.sh"
  end
end
